version: '3'
services:
  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: my-angular-auth
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
    driver: local
